# Generated by Django 4.2.19 on 2025-03-25 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techCLA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
