# Generated by Django 4.2.19 on 2025-02-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techCLA', '0002_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
